# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2019- d3p Developers and their Assignees

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install pytest coverage coveralls
install:
  - pip install -e .
script:
  - coverage run --source d3p -m pytest tests/
after_success:
  - coveralls

notifications:
  email: false