MAJOR_VERSION = 0
MINOR_VERSION = 2
PATCH_VERSION = 0
EXT_VERSION = "alpha"

EXT_VERSION_SUFFIX = f"-{EXT_VERSION}" if len(EXT_VERSION) > 0 else ""

VERSION = f"{MAJOR_VERSION}.{MINOR_VERSION}.{PATCH_VERSION}{EXT_VERSION_SUFFIX}"
