# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2022- d3p Developers and their Assignees

name: Unittests

on:
  push:
    branches: [ "*stable" , "v0.2.0-pypi-release" ]

jobs:
  build_pypi_wheels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build wheel
      run: |
        python -m build
    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*
        name: dist

  upload_pypi_wheels:
    name: Upload wheels to PyPI
    runs-on: ubuntu-latest
    needs:
      - build_pypi_wheels
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Upload to PyPI
        if: contains(github.ref, 'stable')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true

