# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2019- d3p Developers and their Assignees

name: Unittests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, "*stable" ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-cov
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics d3p tests
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics --ignore=E266,E226,W504 d3p tests
    - name: Install dependencies
      run: |
        python -m pip install -e .[compatible-dependencies]
    - name: Test with pytest
      run: |
        pytest --cov=d3p --cov-report term-missing tests/

  reuse-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install reuse
    - name: Reuse compliance
      run: |
        reuse --include-submodules lint
